config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  resources :questions do
    resources :answers, only: [:new, :create, :show, :destroy], shallow: true
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers,   dependent: :destroy

  def author?(resource)
    resource.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_answer,   only: :destroy
  before_action :check_answer_ownership!, only: :destroy

  def create
    @answer = @question.answers.new(answers_params)
    @answer.author = current_user
    if @answer.save
      redirect_to @question
    else
      @answers = @question.answers
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_url(@answer.question)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answers_params
    params.require(:answer).permit(:body)
  end

  def check_answer_ownership!
    redirect_to answer_path(@answer) unless current_user.author?(@answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :check_author!, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers  = @question.answers
    @answer   = Answer.new
  end

  def new
    @question = current_user.questions.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    #byebug
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    #byebug
    redirect_to questions_url
  end

  private
  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def check_author!
    redirect_to question_path(@question) unless current_user.author?(@question)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_owns?(entity)
    current_user&.author?(entity)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  li
    = answer.body
    - if current_user_owns?(answer)
      |
      = link_to t(:delete), answer, method: :delete

app/views/answers/_form.html.slim
- if user_signed_in?
  = render 'shared/error', resource: @answer
  = form_for [@question, @answer] do |f|
    div
      = f.label :body
      = f.text_area :body

    = f.submit t '.create'
- else
  = t('.authentication_required')

app/views/layouts/_header.html.slim
ul
  - if user_signed_in?
    li = link_to t(:log_out, scope: 'devise.links'), destroy_user_session_path, method: :delete
  - else
    li = link_to t(:sign_up, scope: 'devise.links'), new_user_registration_path
    li = link_to t(:sign_in, scope: 'devise.links'), new_user_session_path
div = notice

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackoverflowClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.slim
= form_for @question do |f|
  = render 'shared/error', resource: @question

  div
    = f.label :title
    = f.text_field :title

  div
    = f.label :body
    = f.text_area :body

  = f.submit t '.create'

app/views/questions/_question.html.slim
p = link_to question.title, question

app/views/questions/index.html.slim
h1 hi
= render @questions

= link_to t('.create'), new_question_path

app/views/questions/new.html.slim
= render 'shared/error', resource: @question

= render 'form'

app/views/questions/show.html.slim
dl
  dt = t(:title)
  dd = @question.title

  dt = t(:body)
  dd = @question.body

- if current_user_owns?(@question)
  div = link_to t(:delete), question_path(@question), method: :delete, data: { confirm: t(:sure?) }

ul
  = render @answers
= render 'answers/form'

app/views/shared/_error.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li = message